-- AlterTable
ALTER TABLE `deliveryorder` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    MODIFY `status` ENUM('ASSIGNED', 'ACCEPTED', 'PICKEDUP', 'DELIVERED', 'CANCELLED') NOT NULL DEFAULT 'ASSIGNED';
