version: "3.8"

services:
  app:
    build: .
    restart: always
    env_file: .env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    stdin_open: true
    tty: true
    depends_on:
      - mysqldb
      - mongodb
    networks:
      - backend
  mysqldb:
    image: mysql
    container_name: mysqldb
    restart: always
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_DB_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DB_DATABASE
    ports:
      - $MYSQL_DB_LOCAL_PORT:$MYSQL_DB_DOCKER_PORT
    volumes:
      - mysqldb:/var/lib/mysql
    networks:
      - backend
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_DB_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_DB_DATABASE
    command: ["--bind_ip_all"]
    ports:
      - $MONGO_DB_LOCAL_PORT:$MONGO_DB_DOCKER_PORT
    volumes:
      - mongodb:/data/db
    networks:
      - backend

volumes:
  mysqldb:
  mongodb:

networks:
  backend: