openapi: 3.0.0
info:
  title: ODFDS BackEnd API
  description: ODFDS BackEnd API
  version: 1.0.0
servers:
  - url: http://127.0.0.1:3000
    description: Development Server
tags:
- name: Test

paths:
  /:
    get:
      description: Test API
      tags:
      - Test
      summary: First Test API
      responses:
        '200':
          description: OK
  /restaurant/emailCode:
    get:
      description: Get an email verification code for creating a restaurant account
      tags:
      - Restaurant
      summary: Get an email code
      parameters:
      - in: query
        name: email
        schema: 
          type: string
        required: true
      responses:
        '200':
          description: Email code sent
        '400':
          description: Invalid email format
        '403':
          description: Email is already taken or Code is already sent
        '500':
          description: Can not send out email, server error
  /restaurant:
    get:
      description: Log in an restaurant account and receive a json web token
      tags:
      - Restaurant
      summary: Log in restaurant account
      parameters:
      - in: query
        name: email
        schema: 
          type: string
        required: true
      - in: query
        name: password
        schema: 
          type: string
        required: true
      responses:
        '200':
          description: Login succeed, receive an json web toke
        '400':
          description: Invalid parameters