openapi: 3.0.0
info:
  title: ODFDS BackEnd API
  description: ODFDS BackEnd API
  version: 1.0.0
servers:
  - url: http://127.0.0.1:3000
    description: Development Server
tags:
- name: Test

paths:
  /:
    get:
      description: Test API
      tags:
      - Test
      summary: First Test API
      responses:
        '200':
          description: OK